config/routes.rb
Rails.application.routes.draw do
  resources :todos

  root 'todos#index'

  resources :todos do
    member do
      post 'done'
    end
  end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
    if params[:is_done].present?
      if params[:is_done] == "true"
        @todos = @todos.where(:is_done => true)
      else
        @todos = @todos.where(:is_done => false)
      end
    end
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_path, notice: '已成功建立待辦事項' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todos_path, notice: '已成功編輯待辦事項' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: '已成功刪除待辦事項' }
      format.json { head :no_content }
    end
  end

  def done
    @todo = Todo.find(params[:id])
    if @todo.is_done
      @todo.update_attributes(is_done: false)
    else
      @todo.update_attributes(is_done: true)
    end
    redirect_to(todos_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:content, :is_done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
    <%= f.check_box :is_done, :style => 'visibility: hidden'%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todolist</h1>

<table>
  <thead>
    <tr>
      <th>待辦事項</th>
      <th>狀態</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
    <%=form_tag todos_path,method:"get" do%>
    <%=hidden_field_tag :is_done,true%>
    <%=submit_tag "已完成"%>
    <% end %>
    <%=form_tag todos_path,method:"get" do%>
    <%=hidden_field_tag :is_done,false%>
    <%=submit_tag "未完成"%>
    <% end %>
    <%=form_tag todos_path,method:"get" do%>
    <%=hidden_field_tag :is_done%>
    <%=submit_tag "顯示全部"%>
    <% end %>



    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.content %></td>
        <td>
          <% if todo.is_done %>
          <%= '已完成' %>
          <% else %>
          <%= '未完成' %>
          <% end %>
        </td>
        
        <td>
          <% if todo.is_done %>
          <%= button_to '未完成', done_todo_path(todo), method: :post %>
          <% else %>
          <%= button_to '已完成', done_todo_path(todo), method: :post %>
          <% end %>
        </td>


        
        <td><%= link_to '編輯', edit_todo_path(todo) %></td>
        <td><%= link_to '刪除', todo, method: :delete, data: { confirm: '確定刪除?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新增待辦事項', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @todo.content %>
</p>

<p>
  <strong>Is done:</strong>
  <%= @todo.is_done %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>